server:
  port: 8080

spring:
  application:
    name: k-store-api-gateway
  web:
    resources:
      add-mappings: false
  cloud:
    gateway:
      # Enable service discovery routing
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - StripPrefix=1
      # Additional explicit routes for better control
      routes:
        - id: user-service
          uri: lb://K-STORE-USER-SERVICE
          predicates:
            - Path=/users/**
        - id: user-service-auth
          uri: lb://K-STORE-USER-SERVICE
          predicates:
            - Path=/auth/**
        - id: user-service-health
          uri: http://localhost:8082
          predicates:
            - Path=/user-service/actuator/**
        - id: gateway-actuator
          uri: http://localhost:8080
          predicates:
            - Path=/actuator/**
        - id: product-service
          uri: lb://K-STORE-PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: order-service  
          uri: http://localhost:8084
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/payments/**
        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/notifications/**
      # Compatibility settings
      httpclient:
        connect-timeout: 30000
        response-timeout: 30s
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
