server:
  port: 8080

spring:
  application:
    name: k-store-api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://k-store-user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: product-service
          uri: lb://k-store-product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
        - id: order-service
          uri: lb://k-store-order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=2
        - id: payment-service
          uri: lb://k-store-payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: lb://k-store-notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=2
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
