# Notification Service specific configuration
server:
  port: 8083

spring:
  application:
    name: k-store-notification-service
  datasource:
    url: jdbc:h2:mem:notificationdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

# Kafka Configuration
kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: notification-service
    auto-offset-reset: earliest
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  topics:
    notification-events: notification-events
    bulk-notification-events: bulk-notification-events
    user-events: user-events
    order-events: order-events
    payment-events: payment-events
    product-events: product-events
